pipeline {
    agent any
    environment {
        AWS_REGION = "ap-south-1"
        AWS_DEFAULT_REGION = "ap-south-1"
    }

    stages {
        stage('Terraform Init') {
            steps {
                dir('infra-argocd') {
                    withCredentials([[ 
                        $class: 'AmazonWebServicesCredentialsBinding',
                        credentialsId: 'aws-jenkins-creds',
                        accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                        secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'
                    ]]) {
                        bat "terraform init -force-copy -upgrade"
                    }
                }
            }
        }

        stage('Terraform Validate') {
            steps {
                dir('infra-argocd') {
                    bat "terraform validate"
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('infra-argocd') {
                    withCredentials([[ 
                        $class: 'AmazonWebServicesCredentialsBinding',
                        credentialsId: 'aws-jenkins-creds',
                        accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                        secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'
                    ]]) {
                        bat 'terraform plan -var "vpc_id=%VPC_ID%"'
                    }
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                dir('infra-argocd') {
                    withCredentials([[ 
                        $class: 'AmazonWebServicesCredentialsBinding',
                        credentialsId: 'aws-jenkins-creds',
                        accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                        secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'
                    ]]) {
                        bat '''
                        aws eks update-kubeconfig --region ap-south-1 --name aegonish-eks-cluster
                        terraform apply -auto-approve -var "cluster_name=aegonish-eks-cluster" -var "vpc_id=%VPC_ID%"
                        '''
                    }
                }
            }
        }
    }

    post {
        success {
            echo "✅ ArgoCD infrastructure deployed successfully!"
        }
        failure {
            echo "❌ Terraform failed for ArgoCD infra!"
        }
    }
}
