pipeline {
    agent any
    environment {
        AWS_REGION = "ap-south-1"
        AWS_DEFAULT_REGION = "ap-south-1"
        CLUSTER_NAME = "aegonish-eks-cluster"
    }

    stages {

        stage('Terraform Init') {
            steps {
                dir('infra-argocd') {
                    withCredentials([
                        [$class: 'AmazonWebServicesCredentialsBinding',
                        credentialsId: 'aws-jenkins-creds',
                        accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                        secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']
                    ]) {
                        bat 'terraform init -force-copy -upgrade'
                    }
                }
            }
        }

        stage('Terraform Validate') {
            steps {
                dir('infra-argocd') {
                    bat 'terraform validate'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('infra-argocd') {
                    withCredentials([
                        [$class: 'AmazonWebServicesCredentialsBinding',
                        credentialsId: 'aws-jenkins-creds',
                        accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                        secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'],
                        usernamePassword(credentialsId: 'github-pat', usernameVariable: 'GIT_USER', passwordVariable: 'GIT_TOKEN')
                    ]) {
                        bat '''
echo git_repo_username = "%GIT_USER%" > secrets.auto.tfvars
echo git_repo_token = "%GIT_TOKEN%" >> secrets.auto.tfvars
echo cluster_name = "%CLUSTER_NAME%" >> secrets.auto.tfvars
terraform plan -out=tfplan -var-file=secrets.auto.tfvars
'''
                    }
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                dir('infra-argocd') {
                    withCredentials([
                        [$class: 'AmazonWebServicesCredentialsBinding',
                        credentialsId: 'aws-jenkins-creds',
                        accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                        secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'],
                        usernamePassword(credentialsId: 'github-pat', usernameVariable: 'GIT_USER', passwordVariable: 'GIT_TOKEN')
                    ]) {
                        bat '''
echo git_repo_username = "%GIT_USER%" > secrets.auto.tfvars
echo git_repo_token = "%GIT_TOKEN%" >> secrets.auto.tfvars
echo cluster_name = "%CLUSTER_NAME%" >> secrets.auto.tfvars
terraform apply -auto-approve -var-file=secrets.auto.tfvars
'''
                    }
                }
            }
        }

stage('Set gp2 as Default StorageClass') {
    steps {
        bat '''
echo Setting gp2 StorageClass as default...
powershell "$json = '{\"metadata\":{\"annotations\":{\"storageclass.kubernetes.io/is-default-class\":\"true\"}}}'; kubectl patch storageclass gp2 --type merge -p $json"
echo gp2 StorageClass set as default successfully!
'''
    }
}


    }

    post {
        success {
            echo 'ArgoCD Infra deployed successfully!'
        }
        failure {
            echo 'Terraform failed for ArgoCD Infra!'
        }
    }
}
