pipeline {
    agent any
    environment {
        AWS_REGION = "ap-south-1"
        AWS_DEFAULT_REGION = "ap-south-1"
    }

    stages {
        stage('Terraform Init') {
            steps {
                dir('infra-jenkins') {
                    withCredentials([[
                        $class: 'AmazonWebServicesCredentialsBinding',
                        credentialsId: 'aws-jenkins-creds',
                        accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                        secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'
                    ]]) {
                        bat "terraform init -migrate-state -upgrade"
                    }
                }
            }
        }

        stage('Terraform Validate') {
            steps {
                dir('infra-jenkins') {
                    bat "terraform validate"
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('infra-jenkins') {
                    withCredentials([[
                        $class: 'AmazonWebServicesCredentialsBinding',
                        credentialsId: 'aws-jenkins-creds',
                        accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                        secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'
                    ]]) {
                        bat "terraform plan"
                    }
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                dir('infra-jenkins') {
                    withCredentials([[
                        $class: 'AmazonWebServicesCredentialsBinding',
                        credentialsId: 'aws-jenkins-creds',
                        accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                        secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'
                    ]]) {
                        bat "terraform apply -auto-approve"
                    }
                }
            }
        }
    }

    post {
        success {
            echo "Jenkins Infra deployment complete"
        }
        failure {
            echo "Terraform failed for Jenkins Infra"
        }
    }
}