pipeline {
    agent any
    environment {
        AWS_REGION = "ap-south-1"
    }

    stages {
        stage('Terraform Init') {
            steps {
                dir('infra-jenkins') {
                    bat "terraform init -upgrade"
                }
            }
        }

        stage('Terraform Validate') {
            steps {
                dir('infra-jenkins') {
                    bat "terraform validate"
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('infra-jenkins') {
                    bat "terraform plan"
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                dir('infra-jenkins') {
                    bat "terraform apply -auto-approve"
                }
            }
        }
    }

    post {
        success {
            echo "Jenkins Infra deployment complete"
        }
        failure {
            echo "Terraform failed for Jenkins Infra"
        }
    }
}